### ISSUE TITLE
Filter in IM is not supported when creating sandbox from transformation

### ISSUE THREAD

**Issue by ujovlado** [keboola/transformation-bundle#100]
Input data:

key1 | key2
-- | --
1 | 2
3 | 4
5 | 6
2 | 4

filter in IM:

![screenshot_2018-04-04_22-42-05](https://user-images.githubusercontent.com/419849/38333615-6c8b5780-3859-11e8-8a65-d627bb8edf9d.png)

script:

```python
import csv

with open('in/tables/test.csv', mode='rt', encoding='utf-8') as in_file:
    for line in in_file:
        print(line)

```
actual output:
```
"key1","key2"

"1","2"

"3","4"

"5","6"

"2","4"
```

expected ouput:

```
"key1","key2"

"2","4"
```

**Comment by ondrejhlavacek** [comment]
V jobu, co vytvoří data loader pro storage, chybí filtry

![image](https://user-images.githubusercontent.com/497675/38363556-631ed038-38d5-11e8-8854-148450f49faa.png)

takhle to jde do transformace

![image](https://user-images.githubusercontent.com/497675/38363576-7541d17a-38d5-11e8-9bd7-5e98f3d918d2.png)
