### ISSUE TITLE
Snowflake: do not allow to override STATEMENT_TIMEOUT_IN_SECONDS

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/transformation-bundle#120]
![image](https://user-images.githubusercontent.com/497675/46801944-4a2dc900-cd5c-11e8-9113-d3923326ab39.png)

->

![image](https://user-images.githubusercontent.com/497675/46801968-587be500-cd5c-11e8-8dec-06f755815533.png)

a to jsem to na to testoval!

https://connection.keboola.com/admin/projects/232/transformations/bucket/430264131

tak asi blbě

**Comment by Halama** [comment]
jak to chceš udělat? Jediný spolehlivý je to imho omezit přímo na warehouse https://docs.snowflake.net/manuals/sql-reference/parameters.html#statement-timeout-in-seconds

**Comment by ondrejhlavacek** [comment]
viz https://github.com/keboola/transformation-bundle/pull/121

omezit na warehouse by bylo super, ale to jsme imho dřív zamítli, abychom mohli někomu dát limitem víc. pokud si to pamatuju dobře a stále to platí, tak ze všech nastavených parametrů se vezme ten nejnižší.

**Comment by Halama** [comment]
ten PR jsem zatím minul, mrknu na něj a dám vědět. Myslím ale že to fungovat nebude.
