### ISSUE TITLE
Remove comments - app error on not opened comment

### ISSUE THREAD

**Issue by ErikZigo** [keboola/transformation-bundle#151]
Mam SQL

```sql
CREATE TABLE "XY" AS SELECT * FROM "YZ";
*/
```

Kdyz spustim transformaci tak to skonci na App Erroru pri odstranovani komentaru

```
transformation-858cef179d6970b07faed033f5201088
```
```
message: Notice: Uninitialized string offset: 1
```

Je to pri hledani zacatku toho komentare, ktery  v SQL nemam

**Comment by ErikZigo** [comment]
To by se mohlo odchytit a data jako user error

**Comment by ondrejhlavacek** [comment]
Duplicitní k https://github.com/keboola/transformation-bundle/issues/89

**Comment by ErikZigo** [comment]
Aha sorry to jsem si nevsiml
