### ISSUE TITLE
Transformation class mysql/simple not found

### ISSUE THREAD

**Issue by MiroCillik** [keboola/transformation-bundle#155]
Graph neukaze nic pri tabulke v starej konzole:
https://connection.keboola.com/admin/projects/1305/storage#/tables/out.c-gooddata.CS_Staff

Aj ked je tabulka pouzita v transformacii:
https://connection.keboola.com/admin/projects/1305/transformations/bucket/302004822/transformation/324067505

A ked ju otvorim v novej konzoli, tak vidim error:
https://monosnap.com/file/Q8oQlkLCQ4Q9hCPdf3aTrJ8sXs4TzI

Link na tabulku v novej konzole:
https://connection.keboola.com/admin/projects/1305/storage-explorer/out.c-gooddata/CS_Staff

Vyzera, ze to nejak suvisi s deprekaciou mysql transformaci (?)

**Comment by ondrejhlavacek** [comment]
@MiroCillik uživatel musí transformaci smazat, je deprekovaná.
