### ISSUE TITLE
Better error message

### ISSUE THREAD

**Issue by padak** [keboola/transformation-bundle#156]
If you have issue in input mappings, error job end-up by

![image](https://user-images.githubusercontent.com/1427901/53397679-01437d80-39a8-11e9-9909-c3a4121b4c87.png)

Checking job events also doesn't help you too much :(

![image](https://user-images.githubusercontent.com/1427901/53397716-191b0180-39a8-11e9-8465-976cfdf6e9f0.png)

In this specific case, its super hard to identify where the collision is.

Job: https://connection.keboola.com/admin/projects/2594/jobs/485581679?q=
PT error: https://papertrailapp.com/groups/23635/events?q=transformation-263408d46c216c00feb7fc135ee8a609

Would be great if the error message will be more helpful.

**Comment by ondrejhlavacek** [comment]
@padak bude hláška `Cannot merge mapping from 'in.c-main.source': load type does not match.` lepší? Nebo bys tam ještě vypsal transformace, kterých se to týká? U ostatích konfliktů mergů to transformace nepíše, protože to nedokáže vypsat naráz všechny (pokud jich koliduje víc než 2).

**Comment by padak** [comment]
@ondrejhlavacek jméno src tabulky nebo dst tabulky je posun o 99%. napsat tam jméno transformací je už jen poslední krůček k dokonalosti. Kdybych mohl, napíšu tam jak se jmenují mappingy (co > kam) a v jakých to je transformacích. Cokoliv mezi dnešním stavem a tímhle ideálem je taky velká pomoc.

**Comment by ondrejhlavacek** [comment]
@padak Jak jsem psal, držel bych to spíš konzistentně - u ostatních to nepíše, protože by tě to mohlo potenciálně nasrat. Představil jsem si, že máš 3 kolidující mappingy, zpráva ti ukáže první 2 (ten třetí teď fakt snadno nedohledám), ty ho fixneš, pustíš znovu a dostaneš tu stejnou hlášku jen u jiných transformací - no nenasralo by tě to? Takže bych tam radši dal jen tu informaci, kterou mám zaručeně kompletní.

Nebo by ses na to díval jinak? Poraď

**Comment by padak** [comment]
Neumím tohle posoudit. Pokud to z nějakýho důvodu nevíme, je lepší tam napsat to co víme s tím, že může existovat další zákoutí. Nenapsat nic je podle mě horší než připad, že ukážeme 2 z 3 a upozorníme, že to může po opravení pokračovat "někam dál".

Btw, proč to nevíme? Protože to failne hned a my to nezjišťujeme z cfg, takže odstraněním chyby se posouváš jen do dalšího levelu kde může číhat další error?

p.

**Comment by ondrejhlavacek** [comment]
Tak nějak, neprovádí se žádná "validace", prostě se sestaví něco jako exekuční plán IM pro fázi a v rámci toho sestavování se dělá deduplikace. Jakmile se narazí něco, co nejde rozumně deduplikovat/mergnout, tak se vyhlásí chyba, která okamžitě probublá k uživateli a vše se ukončí. Asi bych to mohl zkusit posbírat vše a vyplivnout nakonec jednu hlášku se všema chybama? Ale to už jsem psal někde, že se mi nelíbí, že to v UI tý chyby bude naplácaný všechno za sebe, takže nějak jako

`Cannot merge mapping from 'in.c-main.source': load type does not match. Check transformations T1 and T2. Cannot merge mapping from 'in.c-main.source': load type does not match. Check transformations T2 and T3.` 

A to mi přijde taky debilní :-( Pokud ale myslíš, že tohle je cajk, můžu to zkusit udělat.
