### ISSUE TITLE
TableImport from workspace source table not found as user error

### ISSUE THREAD

**Issue by pivnicek** [keboola/transformation-bundle#163]
TableImport from workspace should throw UserException if source table not found.
This can occur if temporary tables are used in the transformation output mapping.  the transformation bundle sees them as existing, but they die with that session.

**Comment by ondrejhlavacek** [comment]
`SHOW OBJECTS` zobrazí dostatečný inforamce o tabulce, aby se dalo tady říct, že to je TEMPORARY tabulka a vyhodit chybu.

https://github.com/keboola/transformation-bundle/blob/abc06eba87090eadc52bf4570b5762c55785909c/library/Keboola/Transformation/Backend/Snowflake.php#L399-L409

![image](https://user-images.githubusercontent.com/497675/54593545-1489bc00-4a2f-11e9-8070-794766a889f3.png)
