### ISSUE TITLE
Another treasure?

### ISSUE THREAD

**Issue by odinuv** [keboola/transformation-bundle#191]
![](https://1.bp.blogspot.com/-jxXpJ7Aq09c/WCIoXaq0XzI/AAAAAAAACKs/1Z4iFIb5zWEMy8l4czk3BNiqMf7lI0Y9ACLcB/s1600/Moving-picture-treasure-chest-with-shining-gold-animated-gif.gif)

https://github.com/keboola/transformation-bundle/blob/master/library/Keboola/Transformation/Configuration/Writer/Table.php

https://github.com/keboola/transformation-bundle/blob/master/library/Keboola/Transformation/Configuration/Loader/Table.php

**Comment by ondrejhlavacek** [comment]
jojo, 

![image](https://user-images.githubusercontent.com/497675/56860128-3f9eee00-6993-11e9-819f-ae0cac08d722.png)

duplicita k https://github.com/keboola/transformation-bundle/issues/148 :-)

**Comment by odinuv** [comment]
aaa, prehlidl jsem

**Comment by ondrejhlavacek** [comment]
vpoho, ono to tam přibejvá dost nesystematicky!

**Comment by ondrejhlavacek** [comment]
což mě ale vede k komu, že by to měl bejt spíš projekt a jednotlivý položky issues, hm?
