### ISSUE TITLE
Workspace 39860736 not found

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/transformation-bundle#198]
https://connection.eu-central-1.keboola.com/admin/utils/logs?file=2019/04/30/13/2019-04-30-13-07-04-5cc82c58e7bf4-exception

https://connection.eu-central-1.keboola.com/admin/utils/logs?file=2019/04/30/13/2019-04-30-13-07-04-5cc82c58f3811-log

https://papertrailapp.com/groups/23635/events?q=39860736

nevím, co ho smazalo!

**Comment by ondrejhlavacek** [comment]
takhle vypadal vyfailovanej job

![image](https://user-images.githubusercontent.com/497675/57132557-3ef5c580-6da0-11e9-9ca0-b4b8c2004249.png)

a takhle chvíli před success

![image](https://user-images.githubusercontent.com/497675/57132621-6e0c3700-6da0-11e9-9a87-f4c2c79298dc.png)

běží to každých pár minut a žádnej další error ani před ani po nebyl

my best bet je to, že se odbc driver fakt odhlásil. zatím nechávám otevřený

**Comment by ondrejhlavacek** [comment]
aha, podle cašu to taky mohl bejt opakovanej request curlu/guzzlu bez odpovědi?

**Comment by odinuv** [comment]
mozna? podobna situace https://connection.eu-central-1.keboola.com/admin/projects/250/jobs/42603692?q=%2Bcomponent%3Atransformation%20%2Bparams.config%3A12085483

![image](https://user-images.githubusercontent.com/4319320/57731796-d52cc400-769b-11e9-85b7-146e6f678ff6.png)

https://keboola.slack.com/archives/C02CGK5CL/p1557866476115500

vypada to, ze ho to smazalo, pak se to nejak jalo ho to mazat znovu, to skoncilo 500 protoze `Schema 'KEBOOLA_250.WORKSPACE_42603694' does not exist., SQL state 02000 in SQLPrepare` a nakonec to skoncilo s tim, ze neexistuje

**Comment by ondrejhlavacek** [comment]
@odinuv v PT jsem našel tenhle původní error

```
odbc_prepare(): SQL error: SQL execution internal error:
Processing aborted due to error 300002:3239581272; incident 6134720., SQL state XX000 in SQLPrepare
```
to bylo podle mě po tom, co se provedl output mapping a jali jsme se uklízet workspace. potom teda naběhl záložní cleanup, kterej už správně zahlásil 

```
odbc_prepare(): SQL error: SQL compilation error:
Schema 'KEBOOLA_250.WORKSPACE_42603694' does not exist., SQL state 02000 in SQLPrepare
```

pokud budem mít GC, můžem se na úklid úplně vybodnout a nechat je uklidit samy. 

jestli tomu pomůže přechod na async nebo ne, těžko říct. víc pokazit to rozhodně nemůže.

s touhle issue to ale asi přímo nesouvisí? ta se týká terminovaních procesů (kde může vzniknout error `Workspace 39860736 not found`)

**Comment by odinuv** [comment]
asimasrecht
