### ISSUE TITLE
2016 update 

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/transformation-bundle#21]
# Kroky k postupnému updatu transformací
## 1) UI načítá konfigurace přímo ze storage

Single source of truth, zjednodušení API (odstranění `/configs` z TAPI)
## 2) Lepší popisky změn

Při uložení změny bude UI generovat lepší textové popisky, například přímo názvy transformací, bude umět přidat i metadata, aby bylo možné linkovat. Changelog bucketu bude mnohem informativnější.

Vyžaduje 1) 
## 3) Simple režim

Bude souběžně se stávajícím režimem, default a vynucený pro nové projekty, pro staré se připraví nějaká migrační cesta. Základní featury
- zmizí kategorizace na buckety a transformace (configuration = transformace)
- transformace bude mít jen jednou input a output mapping
- v rámci transformace bude možné mít víc záložek se SQL/R/Python kódem a bude pevně dané pořadí
- zmizí fáze, závislosti a enable/disable
- sandbox dialog buďprovede jen input mapping, nebo dry-run (nebo možná nějaký záložky kódu)
## 4) Verze, publikace

Pouze pro simple režim. Na úrovni transformace umožnit publikovat verze. Vyžaduje změnu 
- v UI
  - u jobu zobrazit id konfigurace
  - readonly režim pro starší konfigurace (pro prolink z jobu a seznamu verzí)
  - texty v sandboxech a runech, že pouští poslední verzi
  - viziuální oznámení, že nejsem v publikované verzi
  - graf závislostí zobrazí vždy aktuální stav zobrazené verze (buď v readonly režimu nějakou starší nebo aktuální), graf by se mohl přesunout na úroveň všech transformací, protože v rámci jedné transformace je vidět, co má za vstupy a výstupy
- v TAPI 
  - aby věděl, jestli má pouštět posledí verzi nebo publikovanou verzi z orchestrátoru
- syrup/queue 
  - logovat verzi pouštěné konfigurace
- orchestrátor
  - ideálně beze změny, bude pouštět tapi a ta si vezme vždy poslední publikovanou verzi (pokud se mu v api callu neřekne jinak, ale to by se mohlo řešit globálně pro všechny komponenty)

**Comment by padak** [comment]
Simple mode se mi líbí, pro malý/levný KBC projekty. Zároveň si myslím že by byla velikánská škoda kdyby nešlo dělat zamotaný transformace, protože když projekt roky kyne, tak se tomu prostě asi nevyhneš. Ty operace co s datama lidi dělaj, jsou někdy komplikovaný a když by všechno bylo lineární, věci by tím sice šly udělat, ale trvaly by dlouho. 

Koukám teď do Firehous projektu, a tam to skoro vypadá, že závislosti moc nepoužívají, v ECH pak dostat položky objednávek znamená tohle: https://dl.dropboxusercontent.com/u/557151/ech-orders-43565423.png což by 100% šlo udělat jednodužší, ale možná by se s tím blbě pracovalo - jak mít všechny zdrojáky mergnutý do jednoho souboru... Slevomat/Rohlík budou určitě reprezentovat "to složitější" spektrum klientů, ale neznamá to, že to je správně!

**Comment by ondrejhlavacek** [comment]
@padak ECH by šlo určitě spojit (a nebo dát jen lineárně za sebe) - btw to je na redshiftu nebo na mysql? závislosti a fáze jsme dělali, abychom se vyhnuli přenosům dat v MySQL. na redshiftu i na snowflaku nic takovýho řešit nemusíme, proto si můžem dovolit to poskládat lineárně za sebe a bez závislostí nebo sdílenýho transformačního workspace a nebude to pomalejší.

**Comment by padak** [comment]
@ondrejhlavacek k vyhnutí se sdílení dat mezi tapi backendama jsme dělali fáze. s těma nemám vuběc problém. ty závislosti mi přijdou nebezpečný dát pryč a jen to linearizovat. na druhou stranu, když ta fáze běží, tak to stejně (z pohledu na konci) je lineární - takže jde asi o to, jestli můžeš pustit libovolnou transformaci nebo musíš pouštět celej bucket - v kostech cejtím, že tohle je jedinej problém, kterej stačí lousknout!

**Comment by ondrejhlavacek** [comment]
@padak @Halama upravil jsem body 3 a 4 a na 1+2 se může začít makat.

**Comment by ondrejhlavacek** [comment]
1+2 hotové
3+4 je nastylované a připravené od Jacka, čekám na Mira s novým style guide
