### ISSUE TITLE
Job cleanup error

### ISSUE THREAD

**Issue by ErikZigo** [keboola/transformation-bundle#216]
Terminoval jsem job transformace `507945220`, ten se provedl ale zalogoval tuhle PHP chybu (i do event v sapi)

```
Error cleaning up workspaces: Catchable Fatal Error: Argument 2 passed to Keboola\TransformationBundle\Job\Cleanup\WorkspaceCleanup::__construct() must implement interface Psr\Log\LoggerInterface, instance of Keboola\Transformation\Log given, called in /www/syrup-router/components/transformation/releases/20190527131109/Job/Executor.php on line 336 and defined
```

`WorkspaceCleanup::__construct()` ocekava jako jeden z argumentu LoggerInterface

Logovaci classa ale tohle rozhranni neimplementuje https://github.com/keboola/transformation-bundle/blob/cae6d5986bb1daf10d86c029328c83cabed015c4/library/Keboola/Transformation/Log.php#L9

**Comment by ondrejhlavacek** [comment]
Ha! Jdu na to
