### ISSUE TITLE
Redshift sandbox z bucketu co je velkejma pismenama

### ISSUE THREAD

**Issue by padak** [keboola/transformation-bundle#36]
Ahoj,
vypadá to na bug v "rychlym" sandboxu. Popsal jsem to celé v ticketu tady: https://keboola.zendesk.com/agent/tickets/5089

Stručně:
"rychlej" sandbox nejde vyrobit z tabulky co je v bucketu jménem in.c-BLABLA.data, ale z in.c-lololo.data ano. V ticketu jsou linky na joby kde to ověřuju že to nejde i že to malejma jde. Poradil jsem jim workaround přes založenou transformaci. Bylo by super to aspoň ale potvrdit, že je to náš bug.

Díky,
Padák the Support :)

**Comment by ondrejhlavacek** [comment]
Fixnuto zde https://github.com/keboola/provisioning-bundle/commit/730cdd9a5037354851b9a2aba7d2d6fb6f30d384
můžeš otestovat, možná bude potřeba dropnout a znovu vytvořit Redshift credentials.

**Comment by padak** [comment]
funguje to super, díky moc!
