### ISSUE TITLE
snowflake: sandbox s už existující tabulkou beží donekonečna

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/transformation-bundle#40]
"Jen chci oznámit že je trochu zvláštní že když sem si teď loadoval snowflake sandbox a neuvědomi sil že už tam mám stejně pojmenovanou tabulku tak ten load běžel do nekonečna a nevypsal bug abych to vyřešil." (https://keboola.zendesk.com/agent/tickets/5307)

**Comment by ondrejhlavacek** [comment]
fixnuto v sapi
