### ISSUE TITLE
Migrace na workspace

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/transformation-bundle#42]
Rozdrobil jsem migraci na workspace na dvě etapy podle backendů. Vše se dostává do produkce dark-launchingem přes featury.
# Workspace
### transformation-input-mapping-direct-simple

(trochu chybně pojmenová featura)

Bylo ještě v době, kdy Storage neumělo input mappingy s filtrama, používalo se u jednoduchých input mappingů bez filtrů, ze Snowflake do Snowflake. Už je kompletně nasazené, featura smazaná.
### transformation-snowflake-input-mapping-direct

Input mappingy ze všech backendů do Snowflake workspace, včetně všech filtrů. Bylo postupně nasazeno v týdnu 29. 8.–2. 9., featura se bude mazat 5. 9.
### transformation-redshift-workspace

Featura je nasazená, ale ještě není zapnutá. Řeší víc věcí zároveň
- přepnutí na `redshift-workspace` provisioning v UI i na backendu
- přepnutí na loady dat do workspace

Upozornění na migraci bylo publikováno 5. 9. na http://status.keboola.com/redshift-transformation-slash-sandbox-provisioning. Zapnutí featury by mělo být bez problému, kromě projektů, kde
- se používá přímý přístup do datových bucketů
- jsou nestadardní COPY OPTIONS

Dark launch proběhne v týdnu od 26. do 30. 9. 
# Timeline
- [x] 7. 9. - Smazat featuru `transformation-snowflake-input-mapping-direct`
- [x] 5. 9. - Identifikovat projekty s přímým přístupem do datových bucketů a napsat jim
- [x] 5. 9. - Identifikovat projekty s nestandardními COPY OPTIONS a napsat jim
- [x] 26. 9.–30. 9. - Dark launch `transformation-redshift-workspace`
- [x] 5. 9. - Vymazat COPY OPTIONS pro projekty s featurou
# Unloady

Unloady dat zůstávají furt stejné, cross backend unloady zatím Storage nepodporuje, tj. na stejném backendu to jde přes Storage, cross backend má staging v S3.

**Comment by ondrejhlavacek** [comment]
Objevil jsem drobnej bug v detekci featury `transformation-snowflake-input-mapping-direct`, takže jí nasazuju dneska znova a její smazání bude až za pár dní.

**Comment by Halama** [comment]
Další krok load workspace jako jeden job https://github.com/keboola/transformation-bundle/issues/44

**Comment by ondrejhlavacek** [comment]
Feature: v UI sandboxů se může volat přímo workspaces API

**Comment by ondrejhlavacek** [comment]
další krok - https://github.com/keboola/kbc-ui/issues/718

**Comment by ondrejhlavacek** [comment]
Jinak je to nasazený a uzavírám
