### ISSUE TITLE
Overit, ci by nebolo mozne urobit loadWorkspace so vsetkymi tabulkami naraz

### ISSUE THREAD

**Issue by ujovlado** [keboola/transformation-bundle#44]
teraz sa to loaduje po jednom a je to relativne velky overhead

**Comment by Halama** [comment]
a hlavne je to kvuli preserve v kazdem loadu stavovy

**Comment by Halama** [comment]
@ondrejhlavacek co myslis o tomhle? Imho jsou tam ty jednotlive loady z historickych duvodu kdy to neumelo mixovane backendy?

**Comment by ondrejhlavacek** [comment]
tohle je v plánu odstranit, jenom nechci dělat moc změn naráz, ale deployovat to atomicky postupně

preserve tam stejně zůstane pro dodatečný loady dat do sandboxu, sandbox je by design stavovej.

**Comment by Halama** [comment]
jo u sandboxu preserve dava smysl ale ne moc u behu transformace. ok

**Comment by padak** [comment]
Udělal jsem test - ty samé tabulky Snowflake Writerem trvají ([1m27s](https://connection.keboola.com/admin/projects/258/jobs/221848532)) a udělat z nich sandbox trvá ([2m48s](https://connection.keboola.com/admin/projects/258/jobs/221849013)). Mergnout to v TAPI by byl ultimátní foršprunk! Teď je to fakt hrozně pomalý :(

**Comment by ondrejhlavacek** [comment]
fixed by bbbbf995980fd0b23bbb8cb473716656db8d950c
