### ISSUE TITLE
Implement Snowflake isUserException

### ISSUE THREAD

**Issue by pivnicek** [keboola/transformation-bundle#58]
https://github.com/keboola/transformation-bundle/blob/master/library/Keboola/Transformation/Backend/Snowflake.php#L730

It can then parse the `Numeric value '' is not recognized, SQL state 22005 in SQLExecDirect` exception as a userException

**Comment by ondrejhlavacek** [comment]
It depends where the error happens. Hard to say without knowing the error context.

**Comment by ondrejhlavacek** [comment]
I believe it comes from this 

https://connection.keboola.com/admin/utils/logs?file=2017/03/16/14/2017-03-16-14-43-57-58ca969d559f5-exception

and that is a duplicate to #57, which is not easy to fix. This error happens on our internal query (getting number of rows on a view) and should not be an user error.
