### ISSUE TITLE
Pořadí transformací

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/transformation-bundle#59]
Vyhodil jsem fáze a závislosti a teď se při puštěným bucketu transformace pouští v nedefinovaném pořadí. Tj. je to nahovno. Je potřeba určit pořadí, ve kterém se budou transformace v bucketu po sobě pouštět.

1) TAPI bude interně sortovat transformace podle nové property `order`
2) UI bude zobrazovat transformace v bucketu seřazené podle property `order` 
3) UI bude umět měnit pořadí 

Vůbec nevím, jak na 3 - v UI vidím 2 možnosti

a) drag & drop jako v orchestracích
b) posun o 1 nahoru a dolů

Ale nevím, jak tuhle property uložit! Bude pravděpodobně uložená u konfiguračního řádku, tj. při každé změně pořadí (a i b) se budou updatovat minimálně 2 řádky (= 2 nové verze) a způsobí to děsnej chaos ve verzích.

Uložit pole s definovaným pořadím do konfigurace bucketu?

**Comment by Halama** [comment]
viděl bych to na podporu v SAPI

**Comment by ondrejhlavacek** [comment]
to by bylo super! možná by se toho na SAPI našlo v tomhle i víc (viz https://github.com/keboola/docker-bundle/issues/150)
