### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/transformation-bundle#65]
V https://github.com/keboola/transformation-bundle/blob/master/library/Keboola/Transformation/Mapping/Input.php#L368 `$dataType` je pole, což nevím jestli je legální, nebo chyba v konfiguraci. V obou případech by to chtělo ošetřit.

`transformation-b7a4d034893bd7b07e35a1c86739dcd5`

![2017-05-30-03-15-11-592cc79fc0f 2017-05-30 07-26-36](https://cloud.githubusercontent.com/assets/215660/26569185/704b3e24-4509-11e7-83a3-349272b04e02.png)

**Comment by ondrejhlavacek** [comment]
Dobrej stopař! Mně to chvíli trvalo, to pole tam je nově správně :-(

**Comment by ondrejhlavacek** [comment]
- [ ] vyřešit merge starýho a novýho datovýho typu (convertEmptyValues...)
 - [ ] uchovat extended datový typ pro load data into workspace

**Comment by ondrejhlavacek** [comment]
- [ ] přidat test na merge, kde nesedí "convertEmptyValuesToNull"

**Comment by JakubMatejka** [comment]
Čoveče, asi to nezabralo, už je to tam dnes zas ;o/ Naposled `transformation-742267f4c2d2196320d7c610bbf50796`

**Comment by JakubMatejka** [comment]
Hm, ale ona to oprava asi ještě není nasazená? Chyba je pořád na stejným řádku, ale v masteru je na něm teď už něco jinýho (konec `if`u)

**Comment by ondrejhlavacek** [comment]
Díky za reopen, jj, ještě jsem to nenasadil, chybu jsem odchytil a do projektu napsal.

**Comment by ondrejhlavacek** [comment]
fixed by fb91148
