### ISSUE TITLE
Don't create credentials only to drop them

### ISSUE THREAD

**Issue by odinuv** [keboola/transformation-bundle#73]
https://keboola.slack.com/archives/C02CGRFHN/p1501758800081640

change https://github.com/keboola/transformation-bundle/blob/master/library/Keboola/Transformation/Backend/Redshift.php#L856 `true` to `false`

**Comment by ondrejhlavacek** [comment]
nojo, jenže ono to je občas potřeba, třeba když vypadne spojení nebo se terminuje transformace v nějakej blbej okamžik

je to tam dost zašmodrchaný :-( ale za předpokladu, že funguje GC, se to asi takhle udělat může!

**Comment by odinuv** [comment]
viz ten slack - nejde o to zrusti to vytvareni tam, ale zrusit ho v pripde ze se  vubec nevytvorilo - zasmodrchany to je - viz ten odkaz na slack

**Comment by odinuv** [comment]
ok, kdyz je ti to proti srsti :), tak co:
```
        $this->connected = false;
        if (!$this->getHost()) {
            $this->initProvisioning();
        }
        $this->connected = true;
```

**Comment by ondrejhlavacek** [comment]
fixed by 914282363d8a9dac5a0d9a7e88e5c47c3fe9f8f8

**Comment by ondrejhlavacek** [comment]
Včera se to nedeploynulo, nasadil jsem to právě teď.
