### ISSUE TITLE
Long commented queries - error without message

### ISSUE THREAD

**Issue by Halama** [keboola/transformation-bundle#76]
Souvisí s https://github.com/keboola/transformation-bundle/issues/49
V helpu u query je sice napsaný že to může failnout ale většinou to člověku nedojde že je to tím.
Jo končí takhle:
![image](https://user-images.githubusercontent.com/903531/29157156-de8e7ce6-7da5-11e7-904e-281630ac5b02.png)

Nezměnilo se něco od té doby co se to debugovalo naposled? Nepomůžou nové drivery? Nebo to hodit na SNFLK support?

Testovací transformace https://connection.keboola.com/admin/projects/236/jobs/306778311

**Comment by ondrejhlavacek** [comment]
Jj, je to segfault a neuděláme s tím u nás nic :-( Leda by syrup-queue do jobu nějaku hlášku dodala.

**Comment by ondrejhlavacek** [comment]
Není to Snowflake specific problém (viz ten https://github.com/keboola/transformation-bundle/issues/49), takže report na Snowflake support je k ničemu - tady máš testy pro všechny DB backendy a všechny failujou úplně stejně

https://connection.keboola.com/admin/projects/232/transformations/bucket/306925099

**Comment by ondrejhlavacek** [comment]
Komentáře imho do queries nepatřej a tenhle problém by mělo řešit nový zjednodušený UI transformací. Tam bychom pak mohli i snadněji uhlídat maximální délku query a v UI ji zalimitovat na 8kb.

Stripovat komentáře z queries teď (regexp) spolehlivě spíš nedokážem, leda přes streaming parser, kterej k tomuhle zmiňuju už pár let. 

Jako workaround by teď mohl bejt nějakej alert v UI, že tam je query >8kb a že to spadne a v transformacích to při takový query nehodit warning do logu, ale rovnou error?

**Comment by ondrejhlavacek** [comment]
Mrknu, jestli by z toho nešel udělat user error na transformacíc rovnou.

**Comment by ondrejhlavacek** [comment]
Upravil jsem logování toho warningu, kterej se dával jen do eventů (01cccf1e0bccb6299e8ffbbadd7b6563d5c77fbe) , že teď bude i v PT, kde se na to zítra podívám, jak to vypadá a pokud to nebude někde divný (vyhodí to notifikaci, ale query nesegfaultne), tak bych to tam rovnou terminoval s user errorem.

**Comment by ondrejhlavacek** [comment]
Deploynuto

**Comment by ondrejhlavacek** [comment]
Tak blbost! Tímhle to není. Dělá to regexp v https://github.com/keboola/transformation-bundle/blob/4bee5929bd9849d94478289e5bbc719a3ea21cd6/library/Keboola/Transformation/Backend/MySql.php#L828 (a ten je i v Redshiftu a Snowflake)

**Comment by ondrejhlavacek** [comment]
Ten regexp slouží k tomu, aby odpálil komentáře a mohl jsem se podívat, jestli query neobsahuje pouze SELECT (to pak může vyčerpat paměť). Našel a upravil jsem nový regexp (https://regex101.com/r/GXb0a5/2, via https://stackoverflow.com/a/31949494/4570977), tak ho nahodím a budu ho chvíli pouštět paralelně s tím původním a detekovat změny. Pokud regexp bude stejně spolehlivý, nahradím jím ten původní.

**Comment by ondrejhlavacek** [comment]
A celý to ještě budu pro jistotu zapínat přes featuru `transformation-sql-comments-stripping`.

**Comment by ondrejhlavacek** [comment]
Nápad: vytáhnout si všechny queries z DB a výsledky naskriptovat a porovnat.

**Comment by ondrejhlavacek** [comment]
Stavím malej tool, kterej si načte tabulku ze Storage a prožene queries oběma regexpama a výsledek porovná. 

https://github.com/ondrejhlavacek/query-regexp

Používám na to tuhle transformaci - https://connection.keboola.com/admin/projects/258/transformations/bucket/configurations/transformation/308390657

Při vývoji jsem si všiml knihovny https://github.com/jdorn/sql-formatter, která umí totéž (`SqlFormatter::removeComments`), tak otestuju obě varianty.

**Comment by ondrejhlavacek** [comment]
Ne všechny queries se mi daří diffovat správně. Starej regexp třeba nechává komentáře po začátku query, takže něco z toho musím odfiltrovat ve skriptu, něco mi zbyde na kontrolu ručně. Projedu obě varianty (upravenej regexp i SqlFormatter::removeComments), i když bych se nejradši přiklonil k použit `SqlFormatter`u, kterej to analyzuje stavovým strojem a umí zhruba všechno co potřebujem (odjebat komentáře, splitovat queries).

**Comment by ondrejhlavacek** [comment]
tak na 120k queries mám zhruba 1800 mismatchů starýho a novýho parsování. někde to je whitespace, budu to muset projet a vymyslet nějaký další pravidla, který ten výběr zúžej

**Comment by ondrejhlavacek** [comment]
Po pár úpravách jich zbylo 1100, jdu to začít procházet ručně, jestli se tam neobjeví ještě nějakej pattern, co by šel vyházet.

**Comment by ondrejhlavacek** [comment]
Notes to self: SQLFormatter nechává prázdnej středník

```
/* ALTER TABLE `orders` ADD INDEX `ID` (`ID`(255)); */

ALTER TABLE `table_increment` ADD INDEX `ID` (`ID`(255));
```

```
/*
 group by
	client_name
;
```
zdá se vyhodnotí SQL Formatter špatně

**Comment by ondrejhlavacek** [comment]
Fixnuto ve forku https://github.com/keboola/sql-formatter

**Comment by ondrejhlavacek** [comment]
Tak po posledních fixech na tapi to na MySQL a Snowflake projde, ale Redshift zdá se segfaultuje ještě někde dál

**Comment by ondrejhlavacek** [comment]
Tak tohle zabralo! https://stackoverflow.com/a/21745209/4570977

**Comment by ondrejhlavacek** [comment]
nasazeno
