### ISSUE TITLE
tag output tables with metadata

### ISSUE THREAD

**Issue by kacurez** [keboola/transformation-bundle#78]
Docker-runner taguje komponenty s componentId + configurationId(vid priklad nizsie) a tie sa este rozlisuju cez `createdBy` a `lastUpdatedBy`. 

U transformaci by to mohlo byt podobne tj `componentId` = 'transformation' a namiesto configurationId tam asi pribudne `bucketId` a `transformationId`? Neviem ci dava zmysel to mat jednotne tj len componentId+configurationId

priklad metadat tabulky otagovanej keboola.ex-db-mysql komponentou:
```
        "metadata": [
            {
                "id": "336328",
                "key": "KBC.createdBy.component.id",
                "value": "keboola.ex-db-mysql",
                "provider": "system",
                "timestamp": "2017-06-01 02:02:09"
            },
            {
                "id": "336329",
                "key": "KBC.createdBy.configuration.id",
                "value": "academy-50",
                "provider": "system",
                "timestamp": "2017-06-01 02:02:09"
            },
            {
                "id": "871597",
                "key": "KBC.lastUpdatedBy.component.id",
                "value": "keboola.ex-db-mysql",
                "provider": "system",
                "timestamp": "2017-07-01 02:02:20"
            },
            {
                "id": "871598",
                "key": "KBC.lastUpdatedBy.configuration.id",
                "value": "academy-50",
                "provider": "system",
                "timestamp": "2017-07-01 02:02:20"
            }
        ]
```

**Comment by pivnicek** [comment]
jo, imho we'll need something parsable like 
`[configId]__[configRowId]`
`[configId]||[configRowId]`
or whatever, for `KBC.lastUpdatedBy.configuration.id`

**Comment by odinuv** [comment]
please no parsing of values :)
configurationId  = bucketId, so all that is needed is tranformationId

**Comment by pivnicek** [comment]
ah, a new key then `KBC.lastUpdatedBy.transformation.id` treba?

**Comment by ondrejhlavacek** [comment]
I would personally skip `transformationId`. It's really hard to track in the code (may be and is in cases ambiguous). In the future I want to flatten the transformation structure and there will be only `configId`.

**Comment by ondrejhlavacek** [comment]
I'll be skipping metadata for buckets, right?

**Comment by ondrejhlavacek** [comment]
If the transformation creates a new table, should it use both `lastUpdatedBy` and `createdBy` keys?

**Comment by kacurez** [comment]
> I'll be skipping metadata for buckets, right?

In my understanding of tables selection via metadata I don't see point in considering buckets.

> If the transformation creates a new table, should it use both lastUpdatedBy and createdBy keys?

I believe yes.
