### ISSUE TITLE
ContextErrorException (0) in SqlFormatter.php line 217: Notice: Uninitialized string offset: 1

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/transformation-bundle#89]
https://connection.keboola.com/admin/utils/logs?file=2017/10/24/21/2017-10-24-21-44-51-59ef98331d0af-exception

**Comment by ErikZigo** [comment]
GG: `Na konci kódu byl zbytek komentáře - > */`

**Comment by ondrejhlavacek** [comment]
Vím, včera jsem si s ním psal, teď to debuguju. 

https://keboola.slack.com/archives/C02D6HRNM/p1508885352000152

**Comment by ondrejhlavacek** [comment]
https://github.com/jdorn/sql-formatter/issues/99

Nemyslím si, že to fixne. Je to zatím ojedinělej bug, takže bych to zatím neřešil. Pokud se to začne objevovat častěji, můžem to aspoň odchytit a vyhlásit nějakou chybu parsování SQL, případně sql-formatter forknout a pofixovat, už tam mám další PR (https://github.com/jdorn/sql-formatter/pull/94)

**Comment by ondrejhlavacek** [comment]
Jako test stačí dát do SQL transformace `*/`.

**Comment by ondrejhlavacek** [comment]
Stačilo by možná chyby z formatteru zahazovat a poslat do DB originální dotaz, případnou chybu ještě může vyhodit DB.

**Comment by JakubMatejka** [comment]
Může se stát, že tuhle chybu vygeneruje i něco jinýho než `*/`, resp. chyba v sql? Pokud ne, tak by se to dalo odchytit a vracet jako user error. Buď rovnou "máš tam konec komentáře navíc", nebo teda obecně "je tam nějaká chyba".

**Comment by ondrejhlavacek** [comment]
Nebo si můžem ten formatter forknout a mergnout PR s fixem, který jim tam už od loňska visí :-)

**Comment by ondrejhlavacek** [comment]
To repo je očividně mrtvý, ale nic lepšího jsem nenašel :-(

**Comment by ondrejhlavacek** [comment]
Bohužel to nedokážu vyřešit přes `UserException`, bude to muset probublat až do Snowflake a hodit chybu tam.

**Comment by ondrejhlavacek** [comment]
![image](https://user-images.githubusercontent.com/497675/52745544-96756800-2fdf-11e9-8cf9-a8a10ba05a92.png)
