### ISSUE TITLE
Graph refactoring

### ISSUE THREAD

**Issue by odinuv** [keboola/transformation-bundle#95]
braindump:
I kdyz se ten graf dneska nedela pres grafovou databazi a jde vzdycky nejak udelat bez ni, prijde mi to uchylny. Pri nedelani pres grafovou databazi s tim musime pracovat vzdycky jako se stromem a to je omezujici a slozity. Omezujici je to proto, ze ten strom musime vzdycky uchopit za tu vec, kterou chceme zobrazit (writer/extractor/transformaci) - tzn. ze pokud se to udela, tak treba pri "poveseni" za tabulku, jsou nasledujici nody transformace, ale uz nelze nijak zjistit/zobrazit, ktery dalsi tabulky do tech transformaci vstupuji (jinak by to nebyl strom). Slozity je to proto, ze ani tak se neda vyhnout cyklum, ktery tam muzou vzniknout a byt legit.

Tzn. prijde mi logicky na to pouzit pravou grafovou databazi. To vylucuje graphql, protoze to neni grafova databaze, protoze vraci stromy a neumi hledat cesty (s libovolnym poctem skoku). Zacal jsem to delat na neo4j, protoze me to kamos doporucil, ze se s tim dobre dela - ma to sandbox/desktop klienta, klienty pro vsechny normalni jazyky, a relativne citelnej dotazovaci jazyk. Vysledek dosavadnich pokusu je v https://github.com/odinuv/graph-experiment coz dela:
- stahne z projektu seznam tabulek
- stahne z projektu vsechny kongiurace a projede IO mappingy
- z toho vygeneruje import pro neo4j
- vymaze databazi, importuje do ni data
- vygeneruje kompletni strukturu projektu: MATCH (Source)-[r]-(Destination) RETURN r,Source,Destination;
- vygeneruje graf, ktery se vazou k necemu: MATCH p = (Source:Source)-[*]->(Destination:Target) WHERE Source.id = $nodeId RETURN  relationships(p) AS rels, nodes(p) AS nodes;
- vygeneruje vsechny grafy, ktere jdou od extractoru k writeru MATCH p = (Source:Source)-[*]->(Destination:Target) RETURN relationships(p) AS rels, nodes(p) AS nodes;
- vylistuje vsechny veci, ktere nejdou od extractoru k writeru MATCH p = (Source:Source)-[*]->(Destination:Target) UNWIND nodes(p) as nds WITH collect(nds) AS nodelist MATCH (n) WHERE NOT (n IN nodelist) RETURN n
- vysledky to generuje do JSONu pro D3

na mym projektu (578), to ma s ~360 nodu, ~150 vazeb zhruba nasledujici casy:
gettables: 1687.2ms
getconfigs: 574.8ms
cleardb: 315ms
importdb: 306.3ms
completegraph: 230ms
querypath: 167ms
querynode: 169.3ms
queryorphan: 109.9ms

coz mi prijde celkem pouzitelny, bylo by zajimavy to spustit vetsim projektu a pokud se to nijak zasadne nezhorsi, tak podle me uplne nejjednodussi prototyp by byl mit nekde jednu  
instanci neo4, ve ktere se pri spusteni sync akce vytvori databaze, naimportuje si to tam ze SAPI konfigurace do projektu, pusti dotaz a smazne to po sobe

Krucialni pro tu grafovou db je mit ten graf dobre udelany (s tim jsem celkem dlouho zapasil), da se sice udelat jakkoliv, ale pokud neni dobre orientovany, tak se ho pitomne pta (+ to trva dyl). Vzhledem k tomu, ze v KBC to tak neni, tak je potreba pri vytvareni toho grafu otacet vazby:
$data[] = "CREATE ($source)-[:READBY]->($nodeId)";
$data[] = "CREATE ($nodeId)-[:WRITES]->($source)";
Potom vyjde graf, kterej v principu respektuje tok dat:
Source (konfigurac ex) -> Table -> Transformace (konfigurace transformace) -> Table -> Destination (konfigurace writeru)

Soucasne verze:
- je plna chyb :)
- splacava transformace (kouka se jen na bucket)
- neresi metadata

Jako nevyhody neo4j se nejcasteji uvadi, ze je to pomaly pro velky grafy, nicmene, co jsem tak pochytil na forech, tak za velky graf se povazuje nejakych 50k-100k vrcholu. To by nas snad nemuselo trapit. Taky si nekdy nekdo stezuje, ze je to nestabilni (jakoze kdyz tam hodi nejaky prase dotaz, tak to spadne) - nevim, nestalo se me to. Spis bych rekl, ze je nestabilni ten desktop klient, ale server bezi furt.

Uricte by se dalo jako alternativa pouzit Amazon Neptune, ale je to zatim v preview verzi, pouziva to na dotazovani teda jinej jazyk - Gremlin, ale mel by mit uplne stejny schopnosti jako Cypher. Importovat data se tam daji pres Gremlin Load Data Format, kterej vypada jako celkem brnkacka (pak to umi jeste RDF, ale k tomu mam odpor). Nijak jsem to nezkousel, protoze me jebalo, ze je k tomu takova sporadicka dokumentace

**Comment by ondrejhlavacek** [comment]
A co kdyby řešením bylo vzít to pouze z metadat tabulek? Tím by zmizely konfigurace, který nikdy nebyly puštěný, apod.

**Comment by odinuv** [comment]
Proc by mely zmizet konfigurace, ktery nebyly nikdy pusteny? Metadata chybi na IM. Krome toho, pokud se zobrazi oboji, tak mame sanci odhalit treba dve konfigurace zapisujici do jedne tabulky

**Comment by ondrejhlavacek** [comment]
Protože nebudou mít nikde svůj podpis v metadatech.

**Comment by odinuv** [comment]
No jasne, ale proc bys jako uzivatel mel chtit tihle konfigurace nevidet? Treba jsi to zacal teprv delat, a jest jsi nepustil writer, ktery ti ty data nekam posle

**Comment by ondrejhlavacek** [comment]
Nevím :-) Zatím jsem vůbec nepřemejšlel, co všechno a jak by to mělo zobrazit, imho to nebude úplně jednoduchý?

**Comment by kacurez** [comment]
tiez si myslim ze to treba dobre premysliet aj z uzivatelskeho hladiska. Zobrazit vsetko naraz imho nieje dobre riesenie. Technicky staci to co navrhuje Odin.

**Comment by odinuv** [comment]
@kacurez a bude se na UI pouzivat to d3? zacal bych treba tim, ze budeme umet u kazdyho objektu (tabulka,konfigurace) zobrazit co se k nemu vaze

**Comment by ondrejhlavacek** [comment]
Padák by to chtěl celý nechat nadesignovat od Jacka

**Comment by kacurez** [comment]
imho by sme mohli vyrobit aspon funkcny prorotyp, aby sme mali my a hlavne Jack lepsiu predstavu o danom probleme. Potom by sa to dorobilo podla Jackovho navrhu.

**Comment by janmichek** [comment]
Chci tady Jackovy predchroustat zadani a sam se v tom zorientovat. Procetl jsem si to a zatim presne nevim co se po nas chce.

Snazim se na to koukat z uzivatelskyho hlediska.
Zatim mam zakladni otazky:
Proc by uzivatele meli koukat do grafu? Nebo co je cilem tohoto tasku obecne?
Jde o nahrazeni Overview sekce v Transofrmacich, zejo?
Mate na mysli neco jako Tableau Prep (summary)? Nebo jde jenom o grafovou vizualizaci bucketu (Neptune)?

![image](https://user-images.githubusercontent.com/15363559/43528476-60f41850-95a9-11e8-9520-14c00f44cb3c.png)

![image](https://user-images.githubusercontent.com/15363559/43528800-185e64e6-95aa-11e8-820e-39a92d68a72e.png)

**Comment by ondrejhlavacek** [comment]
Je to Overview v transformacích a záložka Graph v detailu tabulky v Storage. Obojí je v podstatě stejný.

**Comment by odinuv** [comment]
> Proc by uzivatele meli koukat do grafu

protoze se v projektu nevyznaji, nebo potrebuji zjistit co je na co navazany (odkud se neco bere, nebo kam se neco dostava), podivej se treba na graf u

https://connection.keboola.com/admin/projects/258/storage#/tables/in.c-us-east-1-sapi.projects

**Comment by odinuv** [comment]
+ aby zjistitili co kam pripojeny neni https://paper.dropbox.com/doc/KBC-User-Feedback-all-in-one--AK1CnLrwdOGNl4~w4VNKE_EpAg-oHimQ6JYgI9VKY9gb0nA7#:uid=550417098226729537793943&h2=Storage

**Comment by ondrejhlavacek** [comment]
Kam ten link vede?

**Comment by odinuv** [comment]
hm, na dropbox? :)

**Comment by ondrejhlavacek** [comment]
No u mě to vede na login page :-)

**Comment by odinuv** [comment]
no je to tenhle https://keboola.slack.com/archives/C31U6BGJC/p1534951475000100

**Comment by ondrejhlavacek** [comment]
a teď to vidím, omg.

**Comment by ondrejhlavacek** [comment]
řeší se to v https://github.com/keboola/internal/issues/35, tady zavírám
